name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
      run:  |
        echo $USER
        echo $PASS
        docker build . --file Dockerfile --tag tej-name/dcm_webserver_tej027
        docker login -u $USER -p $PASS
        docker push tej-name/dcm_webserver_tej027
